default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_key_base: 1a022e4f335d24af3d6bd622b9daef5a44808afbe16d4f1c8bed03675ab91ecd9c76ddc1a30f3fbb668b02c00abcba2ecc3714c95943b8f4af86289a2a46d5e1

test:
  secret_key_base: test_secret

staging:
  <<: *default

production:
  <<: *default
