---
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4

commands:
  shared_steps:
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - checkout

      # Install bundler
      - run: gem install bundler:2.3.5

      # Restore Cached Dependencies
      - restore_cache:
          name: Restore bundle cache
          key: administrate-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore npm cache
          key: administrate-{{ checksum "package-lock.json" }}

      # Install dependencies
      - run: bundle install --path vendor/bundle
      - run: npm install

      # Cache Dependencies
      - save_cache:
          name: Store bundle cache
          key: administrate-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          name: Store npm cache
          key: administrate-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec

      # Check vulnerabilities
      - run: bundle exec rake bundler:audit

default_job: &default_job
  working_directory: ~/administrate

jobs:
  ruby-26:
    <<: *default_job
    steps:
      - shared_steps
      # Run the tests against the versions of Rails that support Ruby 2.6
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rails50 rspec
      - run: bundle exec appraisal rails51 rspec
      - run: bundle exec appraisal rails52 rspec
      - run: bundle exec appraisal rails60 rspec
      - run: bundle exec appraisal rails61 rspec
    docker:
      - image: cimg/ruby:2.6-browsers
        environment:
          PGHOST: localhost
          PGUSER: administrate
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby26
          POSTGRES_PASSWORD: ""

  ruby-27:
    <<: *default_job
    steps:
      - shared_steps
      # Run the tests against the versions of Rails that support Ruby 2.7
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rails50 rspec
      - run: bundle exec appraisal rails51 rspec
      - run: bundle exec appraisal rails52 rspec
      - run: bundle exec appraisal rails60 rspec
      - run: bundle exec appraisal rails61 rspec
      - run: bundle exec appraisal rails70 rspec
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          PGHOST: localhost
          PGUSER: administrate
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby27
          POSTGRES_PASSWORD: ""

  ruby-30:
    <<: *default_job
    steps:
      - shared_steps
      # Run the tests against the versions of Rails that support Ruby 3.0
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rails60 rspec
      - run: bundle exec appraisal rails61 rspec
      - run: bundle exec appraisal rails70 rspec
    docker:
      - image: cimg/ruby:3.0-browsers
        environment:
          PGHOST: localhost
          PGUSER: administrate
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby30
          POSTGRES_PASSWORD: ""

  ruby-31:
    <<: *default_job
    steps:
      - shared_steps
      # Run the tests against the versions of Rails that support Ruby 3.1
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rails61 rspec
      - run: bundle exec appraisal rails70 rspec
    docker:
      - image: cimg/ruby:3.1-browsers
        environment:
          PGHOST: localhost
          PGUSER: administrate
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby31
          POSTGRES_PASSWORD: ""

workflows:
  version: 2
  multiple-rubies:
    jobs:
      - ruby-31
      - ruby-30
      - ruby-27
      - ruby-26
