---
name: Bundler Audit
on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Bundler Audit'
        uses: thoughtbot/bundler-audit-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
